import type { Course } from "../types";

export const mockCourses: Course[] = [
    {
        id: "1",
        title: "React do zero ao avançado",
        slug: "react-zero-avancado",
        description: "Aprenda React do básico ao avançado com projetos práticos.",
        thumbnailUrl: "https://placehold.co/600x340/3B82F6/ffffff?text=React",
        instructorId: "i1",
        instructor: { id: "i1", name: "Pedro Souza", avatarUrl: "" },
        price: 197,
        level: "intermediate",
        status: "published",
        categoryId: "tech",
        tags: ["react", "javascript"],
        totalDurationSeconds: 36000,
        totalLessons: 20,
        enrollmentCount: 1200,
        rating: 4.9,
        ratingCount: 340,
        modules: [],
        createdAt: "2024-01-01",
        updatedAt: "2024-01-01",
    },
    {
        id: "2",
        title: "UI Design para iniciantes",
        slug: "ui-design-iniciantes",
        description: "Aprenda os fundamentos do design de interfaces.",
        thumbnailUrl: "https://placehold.co/600x340/10B981/ffffff?text=Design",
        instructorId: "i2",
        instructor: { id: "i2", name: "Ana Lima", avatarUrl: "" },
        price: 0,
        level: "beginner",
        status: "published",
        categoryId: "design",
        tags: ["design", "ui", "ux"],
        totalDurationSeconds: 18000,
        totalLessons: 18,
        enrollmentCount: 3400,
        rating: 4.7,
        ratingCount: 210,
        modules: [],
        createdAt: "2024-01-01",
        updatedAt: "2024-01-01",
    },
    {
        id: "3",
        title: "Marketing digital e growth",
        slug: "marketing-digital-growth",
        description: "Estratégias avançadas de marketing e crescimento.",
        thumbnailUrl: "https://placehold.co/600x340/F59E0B/ffffff?text=Marketing",
        instructorId: "i3",
        instructor: { id: "i3", name: "Carlos Melo", avatarUrl: "" },
        price: 297,
        level: "advanced",
        status: "published",
        categoryId: "marketing",
        tags: ["marketing", "growth"],
        totalDurationSeconds: 28800,
        totalLessons: 24,
        enrollmentCount: 890,
        rating: 5.0,
        ratingCount: 180,
        modules: [],
        createdAt: "2024-01-01",
        updatedAt: "2024-01-01",
    },
    {
        id: "4",
        title: "Inteligência artificial na prática",
        slug: "ia-na-pratica",
        description: "Use IA no seu dia a dia com ferramentas modernas.",
        thumbnailUrl: "https://placehold.co/600x340/8B5CF6/ffffff?text=IA",
        instructorId: "i4",
        instructor: { id: "i4", name: "Julia Neves", avatarUrl: "" },
        price: 247,
        level: "intermediate",
        status: "published",
        categoryId: "tech",
        tags: ["ia", "machine learning"],
        totalDurationSeconds: 32400,
        totalLessons: 22,
        enrollmentCount: 2100,
        rating: 4.8,
        ratingCount: 290,
        modules: [],
        createdAt: "2024-01-01",
        updatedAt: "2024-01-01",
    },
];